input: touchscreen: st: Don't redefine u8, u16, and u32
Clang warns a lot in this driver along the lines of:

In file included from
../drivers/input/touchscreen/st/fts_lib/ftsGesture.c:19:
In file included from
../drivers/input/touchscreen/st/fts_lib/ftsIO.h:17:
In file included from
../drivers/input/touchscreen/st/fts_lib/ftsCrossCompile.h:4:
In file included from ../include/linux/init.h:4:
In file included from ../include/linux/compiler.h:220:
In file included from ../include/uapi/linux/types.h:4:
In file included from arch/arm64/include/generated/asm/types.h:1:
In file included from ../include/uapi/asm-generic/types.h:6:
../include/asm-generic/int-ll64.h:16:23: warning: redefinition of
typedef 'u8' is a C11 feature [-Wtypedef-redefinition]
typedef unsigned char u8;
                      ^
../drivers/input/touchscreen/st/fts_lib/ftsSoftware.h:18:23: note:
previous definition is here
typedef unsigned char u8;
                      ^

Fixes: ed29ea5a01b9 ("input: touchpanel: Add ST Touchscreen version 4.1.0 driver")
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>